import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, Navigate, useLocation } from 'react-router-dom';
import { useState } from 'react';
import { toast } from 'sonner';
import { api, unwrap } from '../api/client';
import { money } from '../lib/utils';
import type { Order } from '../types';

export default function AccountPage(){const path=useLocation().pathname;if(!localStorage.getItem('cokhi_token'))return <Navigate to="/login" replace/>;return <section className="section bg-surface"><div className="container"><p className="eyebrow">TÀI KHOẢN KHÁCH HÀNG</p><h1 className="title mt-2">Tài khoản của tôi</h1><div className="mt-7 grid gap-6 md:grid-cols-[230px_1fr]"><nav className="h-fit border border-line bg-white p-3">{[['/account','Hồ sơ'],['/account/orders','Đơn hàng'],['/account/addresses','Địa chỉ giao hàng'],['/account/posts','Bài viết của tôi']].map(([to,label])=><Link key={to} className={`block p-3 font-bold hover:text-red ${path===to?'bg-surface text-red':''}`} to={to}>{label}</Link>)}</nav>{path.endsWith('/orders')?<Orders/>:path.endsWith('/addresses')?<Addresses/>:<Profile/>}</div></div></section>}
function Profile(){const qc=useQueryClient();const{data}=useQuery({queryKey:['profile'],queryFn:()=>api.get('/user/profile').then(unwrap<any>)});const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api.put('/user/profile',{fullName:f.get('fullName'),phone:f.get('phone')});const current=JSON.parse(localStorage.getItem('cokhi_user')||'{}');localStorage.setItem('cokhi_user',JSON.stringify({...current,fullName:f.get('fullName'),phone:f.get('phone')}));qc.invalidateQueries({queryKey:['profile']});toast.success('Đã cập nhật hồ sơ');};return <form onSubmit={save} className="border border-line bg-white p-6"><h2 className="text-2xl font-black">Thông tin cá nhân</h2><p className="mt-2 text-slate-500">Dùng thông tin này khi đặt hàng và nhận tư vấn.</p><label className="label mt-6">Họ và tên</label><input name="fullName" required className="field max-w-xl" defaultValue={data?.fullName} key={data?.fullName}/><label className="label mt-4">Email</label><input readOnly className="field max-w-xl bg-slate-50 text-slate-500" value={data?.email||''}/><label className="label mt-4">Số điện thoại</label><input name="phone" className="field max-w-xl" defaultValue={data?.phone} key={data?.phone}/><button className="btn mt-6 bg-red text-white">Lưu hồ sơ</button></form>}
function Orders(){const{data=[]}=useQuery({queryKey:['my-orders'],queryFn:()=>api.get('/user/orders').then(unwrap<Order[]>)});return <div><h2 className="text-2xl font-black">Đơn hàng của tôi</h2>{data.map(o=><div className="mt-4 border border-line bg-white p-5" key={o.orderCode}><div className="flex flex-wrap justify-between gap-3"><div><b className="text-navy">{o.orderCode}</b><p className="mt-1 text-sm text-slate-500">{o.status} · {o.items.length} sản phẩm · {new Date(o.createdAt).toLocaleDateString('vi-VN')}</p></div><b className="text-red">{money(o.grandTotal)}</b></div><div className="mt-4 flex flex-wrap gap-2">{o.items.map((i)=><span key={i.productId} className="bg-surface px-3 py-2 text-sm">{i.productName} × {i.quantity}</span>)}</div></div>)}{!data.length&&<div className="mt-4 bg-white p-8 text-slate-500">Bạn chưa có đơn hàng nào.</div>}</div>}
function Addresses(){const qc=useQueryClient();const{data=[]}=useQuery({queryKey:['my-addresses'],queryFn:()=>api.get('/user/addresses').then(unwrap<any[]>)});const[provinceCode,setProvince]=useState('');const provinces=useQuery({queryKey:['provinces'],queryFn:()=>api.get('/address/provinces').then(unwrap<any[]>)});const wards=useQuery({queryKey:['wards',provinceCode],queryFn:()=>api.get('/address/wards',{params:{provinceCode}}).then(unwrap<any[]>),enabled:!!provinceCode});const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const province=provinces.data?.find((x:any)=>x.code===provinceCode);const ward=wards.data?.find((x:any)=>x.code===String(f.get('wardCode')));await api.post('/user/addresses',{recipientName:f.get('recipientName'),phone:f.get('phone'),provinceCode,provinceName:province?.name,wardCode:f.get('wardCode'),wardName:ward?.name,addressLine:f.get('addressLine'),isDefault:f.get('isDefault')==='on'});toast.success('Đã lưu địa chỉ');e.currentTarget.reset();setProvince('');qc.invalidateQueries({queryKey:['my-addresses']});};const remove=async(id:number)=>{await api.delete(`/user/addresses/${id}`);toast.success('Đã xóa địa chỉ');qc.invalidateQueries({queryKey:['my-addresses']});};return <div><h2 className="text-2xl font-black">Địa chỉ giao hàng</h2><div className="mt-4 space-y-3">{data.map((a:any)=><div className="flex flex-wrap items-start justify-between gap-3 border border-line bg-white p-5" key={a.id}><div><b>{a.recipientName} · {a.phone}</b><p className="mt-1 text-slate-600">{a.addressLine}, {a.wardName}, {a.provinceName}</p>{a.isDefault&&<small className="mt-2 inline-block font-bold text-emerald-700">Địa chỉ mặc định</small>}</div><button onClick={()=>remove(a.id)} className="text-sm font-bold text-red">Xóa</button></div>)}</div><form onSubmit={save} className="mt-5 border border-line bg-white p-5"><h3 className="text-lg font-black">Thêm địa chỉ mới</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required name="recipientName" className="field" placeholder="Người nhận"/><input required name="phone" className="field" placeholder="Số điện thoại"/><select required value={provinceCode} onChange={e=>setProvince(e.target.value)} className="field"><option value="">Tỉnh / thành phố</option>{provinces.data?.map((p:any)=><option key={p.code} value={p.code}>{p.name}</option>)}</select><select required name="wardCode" disabled={!provinceCode} className="field"><option value="">Phường / xã</option>{wards.data?.map((w:any)=><option key={w.code} value={w.code}>{w.name}</option>)}</select><input required name="addressLine" className="field sm:col-span-2" placeholder="Số nhà, đường, khu công nghiệp"/></div><label className="mt-4 flex items-center gap-2 text-sm font-bold"><input name="isDefault" type="checkbox"/>Đặt làm địa chỉ mặc định</label><button className="btn mt-4 bg-red text-white">Lưu địa chỉ</button></form></div>}
