import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { api, unwrap } from '../api/client';
import { money } from '../lib/utils';
import type { Order, Product } from '../types';
import AdminContentPage from './AdminContentPage';

export default function AdminPage() {
  const { section } = useParams();
  if (section === 'products') return <Products/>;
  if (section === 'categories') return <Categories/>;
  if (section === 'orders') return <Orders/>;
  if (section === 'quotes') return <Quotes/>;
  if (section === 'vat') return <Vats/>;
  if (section === 'articles') return <AdminContentPage kind="articles"/>;
  if (section === 'services') return <AdminContentPage kind="services"/>;
  if (section === 'videos') return <AdminContentPage kind="videos"/>;
  if (section === 'users') return <Users/>;
  if (section === 'settings') return <Settings/>;
  return <Dashboard/>;
}

function Dashboard() {
  const { data } = useQuery({ queryKey: ['admin-dashboard'], queryFn: () => api.get('/admin/dashboard').then(unwrap<any>) });
  const stats = [['Sản phẩm', data?.products ?? '—'], ['Khách hàng', data?.users ?? '—'], ['Đơn hàng', data?.orders ?? '—'], ['Chờ xử lý', data?.pendingOrders ?? '—']];
  return <><Head title="Tổng quan vận hành" hint="Bảng điều khiển Bảo Tín · dữ liệu demo cập nhật ngay khi thao tác"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([k,v]) => <div className="admin-stat" key={k}><small>{k}</small><b>{v}</b><span>Đang hoạt động</span></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="admin-panel"><h2 className="text-xl font-black">Hoạt động cửa hàng</h2><p className="mt-2 text-sm text-slate-500">Tổng quan danh mục máy nén khí, phụ tùng và yêu cầu dịch vụ.</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="bg-surface p-5"><small className="text-slate-500">Giá trị đơn demo</small><b className="mt-2 block text-2xl text-navy">{money(data?.revenue || 1285000000)}</b></div><div className="bg-surface p-5"><small className="text-slate-500">Yêu cầu báo giá</small><b className="mt-2 block text-2xl text-red">{data?.quotes ?? 12}</b></div></div></section><section className="admin-panel"><h2 className="text-xl font-black">Việc cần làm</h2><div className="mt-4 space-y-3"><Quick title="Xử lý yêu cầu báo giá" value="2 khách hàng cần phản hồi"/><Quick title="Kiểm tra đơn hàng mới" value="5 đơn đang chờ xác nhận"/><Quick title="Cập nhật nội dung" value="3 bài viết chờ duyệt"/></div></section></div></>;
}
function Products() {
  const qc = useQueryClient(); const { data = [] } = useQuery({ queryKey: ['admin-products'], queryFn: () => api.get('/admin/products').then(unwrap<Product[]>) });
  const create = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = e.currentTarget; const f = new FormData(form); try { await api.post('/admin/products', { name: f.get('name'), slug: f.get('slug'), sku: f.get('sku'), categoryId: Number(f.get('categoryId')) || 1, price: Number(f.get('price')) || null, priceType: f.get('priceType'), stockQuantity: Number(f.get('stockQuantity')) || 0, thumbnailUrl: f.get('thumbnailUrl') || 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=84', status: 'ACTIVE', featured: false, shortDescription: f.get('description') }); toast.success('Đã thêm sản phẩm vào catalogue'); form.reset(); qc.invalidateQueries({ queryKey: ['admin-products'] }); qc.invalidateQueries({ queryKey: ['products'] }); } catch { toast.error('Không thể lưu sản phẩm'); } };
  const remove=async(id:number)=>{if(!window.confirm('Ẩn sản phẩm này khỏi catalogue?'))return;await api.delete(`/admin/products/${id}`);toast.success('Đã ẩn sản phẩm');qc.invalidateQueries({queryKey:['admin-products']});qc.invalidateQueries({queryKey:['products']});};return <><Head title="Quản lý sản phẩm" hint="Tạo sản phẩm, thiết lập giá và xem danh mục đang kinh doanh."/><form onSubmit={create} className="admin-panel mb-6"><h2 className="mb-4 text-lg font-black">Thêm sản phẩm mới</h2><div className="grid gap-3 md:grid-cols-3"><input required name="name" className="field" placeholder="Tên sản phẩm"/><input required name="slug" className="field" placeholder="Đường dẫn (slug)"/><input required name="sku" className="field" placeholder="Mã SKU"/><input name="price" type="number" className="field" placeholder="Giá bán (VNĐ)"/><select name="priceType" className="field"><option value="FIXED">Niêm yết giá</option><option value="QUOTE">Yêu cầu báo giá</option><option value="CONTACT">Liên hệ</option></select><select name="categoryId" className="field"><option value="1">Máy nén khí</option><option value="2">Máy sấy khí</option><option value="3">Lọc đường ống</option><option value="4">Bình tích áp</option><option value="5">Dầu máy nén khí</option><option value="6">Phụ tùng</option><option value="7">Máy tạo khí Nitơ</option><option value="8">Máy bơm chân không</option></select><input name="stockQuantity" type="number" defaultValue="10" className="field" placeholder="Tồn kho"/><input name="thumbnailUrl" className="field md:col-span-2" placeholder="URL hình ảnh (có thể để trống)"/><input name="description" className="field md:col-span-2" placeholder="Mô tả ngắn"/><button className="btn bg-red text-white">Thêm sản phẩm</button></div></form><Table heads={['Sản phẩm','Danh mục','Mã SKU','Giá','Kho','Trạng thái','Thao tác']} rows={data.map((p) => [<span className="flex items-center gap-3"><img src={p.thumbnailUrl} className="h-12 w-14 object-cover"/><b>{p.name}</b></span>,p.category?.name || 'Máy nén khí',p.sku,p.priceType === 'FIXED' ? money(p.salePrice || p.price) : 'Liên hệ',`${p.stockQuantity} sản phẩm`,<span className="status-pill">Đang bán</span>,<button className="font-bold text-red" onClick={()=>remove(p.id)}>Ẩn sản phẩm</button>])}/></>;
}
function Categories() { const qc=useQueryClient();const { data=[] } = useQuery({ queryKey: ['categories'], queryFn: () => api.get('/admin/categories').then(unwrap<any[]>) });const add=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const name=String(f.get('name'));const slug=String(f.get('slug')||name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));await api.post('/admin/categories',{name,slug,parentId:Number(f.get('parentId'))||null});toast.success('Đã thêm danh mục');form.reset();qc.invalidateQueries({queryKey:['categories']});};return <><Head title="Danh mục sản phẩm" hint="Tổ chức catalogue thành nhóm chính và danh mục con trong menu."/><form onSubmit={add} className="admin-panel mb-5"><h2 className="mb-4 text-lg font-black">Thêm danh mục</h2><div className="grid gap-3 sm:grid-cols-[1fr_1fr_1fr_auto]"><input required name="name" className="field" placeholder="Tên danh mục"/><input name="slug" className="field" placeholder="Slug (tự tạo nếu để trống)"/><select name="parentId" className="field"><option value="">Danh mục chính</option>{data.filter((c:any)=>!c.parentId).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn bg-red text-white">Thêm danh mục</button></div></form><div className="admin-panel"><div className="grid gap-3 md:grid-cols-3">{data.map((c:any) => <div key={c.id} className="flex items-start gap-3 border border-line p-4"><span className="grid h-10 w-10 shrink-0 place-items-center bg-navy text-yellow">{c.parentId ? '↳' : 'BT'}</span><div><b>{c.name}</b><small className="mt-1 block text-slate-500">{c.parentId ? 'Danh mục con' : 'Danh mục chính'} · /{c.slug}</small></div></div>)}</div></div></>; }
function Orders() { const qc=useQueryClient(); const { data=[] }=useQuery({ queryKey:['admin-orders'], queryFn:()=>api.get('/admin/orders').then(unwrap<Order[]>) }); const change=async(code:string,status:string)=>{await api.patch(`/admin/orders/${code}/status`,null,{params:{status}});toast.success('Đã cập nhật trạng thái đơn');qc.invalidateQueries({queryKey:['admin-orders']});qc.invalidateQueries({queryKey:['admin-dashboard']});}; return <><Head title="Quản lý đơn hàng" hint="Theo dõi thông tin giao nhận và cập nhật tiến độ xử lý."/><div className="space-y-4">{data.map(o=><div key={o.orderCode} className="admin-panel"><div className="flex flex-wrap items-start justify-between gap-4"><div><b className="text-lg text-navy">{o.orderCode}</b><p className="mt-1 text-sm text-slate-600">{o.customerName} · {o.customerPhone}</p><p className="text-sm text-slate-500">{o.shippingFullAddress}</p></div><div className="text-right"><b className="text-xl text-red">{money(o.grandTotal)}</b><small className="mt-1 block text-slate-500">{o.items.length} sản phẩm</small></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4"><span className="text-sm text-slate-500">{o.payment.method} · {o.payment.status} {o.vat ? '· Có yêu cầu VAT' : ''}</span><select className="field w-52" value={o.status} onChange={e=>change(o.orderCode,e.target.value)}>{['PENDING','CONFIRMED','PROCESSING','SHIPPING','COMPLETED','CANCELLED'].map(x=><option key={x} value={x}>{statusName(x)}</option>)}</select></div></div>)}</div>{!data.length&&<div className="admin-panel text-slate-500">Chưa có đơn hàng mới. Đơn hàng khách đặt sẽ xuất hiện tại đây.</div>}</>; }
function Quotes() { const qc=useQueryClient(); const { data=[] }=useQuery({queryKey:['admin-quotes'],queryFn:()=>api.get('/admin/quotes').then(unwrap<any[]>)}); const change=async(id:number,status:string)=>{await api.patch(`/admin/quotes/${id}/status`,null,{params:{status}});qc.invalidateQueries({queryKey:['admin-quotes']});toast.success('Đã cập nhật yêu cầu báo giá');}; return <><Head title="Yêu cầu báo giá" hint="Thông tin khách hàng gửi từ form tư vấn sản phẩm."/><Table heads={['Khách hàng','Sản phẩm / nhu cầu','Liên hệ','Trạng thái']} rows={data.map(q=>[<><b>{q.name}</b><small className="block text-slate-500">{q.company}</small></>,q.productName||'Tư vấn chung',<><a className="font-bold text-navy" href={`tel:${q.phone}`}>{q.phone}</a><small className="block text-slate-500">{q.email}</small></>,<select className="field min-w-36" value={q.status} onChange={e=>change(q.id,e.target.value)}>{['NEW','CONTACTED','QUOTED','WON','LOST'].map(x=><option key={x} value={x}>{statusName(x)}</option>)}</select>])}/></>; }
function Vats() { const qc=useQueryClient(); const {data=[]}=useQuery({queryKey:['admin-vats'],queryFn:()=>api.get('/admin/vat-invoices').then(unwrap<any[]>)}); const change=async(id:number,status:string)=>{await api.patch(`/admin/vat-invoices/${id}/status`,null,{params:{status}});qc.invalidateQueries({queryKey:['admin-vats']});}; return <><Head title="Yêu cầu hóa đơn VAT" hint="Quản lý thông tin xuất hóa đơn được khách hàng gửi kèm đơn hàng."/><Table heads={['Mã đơn','Doanh nghiệp / MST','Email kế toán','Trạng thái']} rows={data.map(v=>[v.orderCode,<><b>{v.companyName}</b><small className="block text-slate-500">MST {v.taxCode}</small></>,v.invoiceEmail,<select className="field min-w-36" value={v.status} onChange={e=>change(v.id,e.target.value)}>{['REQUESTED','PROCESSING','ISSUED','REJECTED'].map(x=><option key={x} value={x}>{statusName(x)}</option>)}</select>])}/></>; }
function Moderation() { const qc=useQueryClient(); const {data=[]}=useQuery({queryKey:['admin-articles'],queryFn:()=>api.get('/admin/articles').then(unwrap<any[]>)}); const moderate=async(id:number,status:string)=>{await api.patch(`/admin/articles/${id}/moderate`,null,{params:{status}});toast.success('Đã cập nhật bài viết');qc.invalidateQueries({queryKey:['admin-articles']});}; return <><Head title="Bài viết & kiến thức" hint="Duyệt nội dung hướng dẫn kỹ thuật trước khi đăng."/><Table heads={['Tiêu đề','Tác giả','Ngày gửi','Trạng thái / thao tác']} rows={data.map(a=>[<b>{a.title}</b>,a.author,a.publishedAt,<div className="flex flex-wrap items-center gap-2"><span className="status-pill">{a.status||'PENDING'}</span><button className="btn bg-navy px-3 text-white" onClick={()=>moderate(a.id,'PUBLISHED')}>Duyệt</button><button className="btn btn-outline px-3" onClick={()=>moderate(a.id,'REJECTED')}>Từ chối</button></div>])}/></>; }
function Users() { const {data=[]}=useQuery({queryKey:['admin-users'],queryFn:()=>api.get('/admin/users').then(unwrap<any[]>)}); return <><Head title="Khách hàng" hint="Danh sách tài khoản đã tạo trên cửa hàng Bảo Tín."/><Table heads={['Khách hàng','Email','Vai trò','Trạng thái']} rows={data.map(u=>[u.fullName,u.email,u.role==='ADMIN'?'Quản trị viên':'Khách hàng',<span className="status-pill">{u.status||'ACTIVE'}</span>])}/></>; }
function Settings() { const {data}=useQuery({queryKey:['admin-settings'],queryFn:()=>api.get('/admin/settings').then(unwrap<any>)});const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api.put('/admin/settings',Object.fromEntries(f.entries()));toast.success('Đã lưu thông tin cửa hàng');}; return <><Head title="Cài đặt cửa hàng" hint="Thông tin liên hệ và hỗ trợ khách hàng hiển thị trên website."/><form onSubmit={save} className="admin-panel max-w-3xl"><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Tên doanh nghiệp</span><input name="companyName" className="field" defaultValue={data?.companyName} key={data?.companyName}/></label><label><span className="label">Hotline bán hàng</span><input name="hotline" className="field" defaultValue={data?.hotline} key={data?.hotline}/></label><label><span className="label">Email liên hệ</span><input name="email" className="field" defaultValue={data?.email} key={data?.email}/></label><label><span className="label">Hỗ trợ kỹ thuật</span><input name="technicalPhone" className="field" defaultValue={data?.technicalPhone||'0983 755 949'} key={data?.technicalPhone}/></label><label className="sm:col-span-2"><span className="label">Địa chỉ</span><input name="address" className="field" defaultValue={data?.address||'P.305, Tòa C2 Megastar, Xuân Đỉnh, Bắc Từ Liêm, Hà Nội'} key={data?.address}/></label></div><button className="btn mt-5 bg-red text-white">Lưu thay đổi</button></form></>; }
function Head({title,hint}:{title:string;hint:string}) { return <div className="mb-6"><p className="eyebrow">BAO TIN · ADMIN</p><h1 className="mt-2 text-3xl font-black text-navy">{title}</h1><p className="mt-2 text-slate-500">{hint}</p></div>; }
function Table({heads,rows}:{heads:string[];rows:any[][]}) { return <div className="admin-panel overflow-x-auto !p-0"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-navy text-white"><tr>{heads.map(h=><th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} className="border-t border-line align-middle hover:bg-surface">{r.map((c,j)=><td key={j} className="px-5 py-4">{c}</td>)}</tr>):<tr><td className="p-10 text-center text-slate-500" colSpan={heads.length}>Chưa có dữ liệu</td></tr>}</tbody></table></div>; }
function Quick({title,value}:{title:string;value:string}) { return <div className="border-l-2 border-yellow bg-surface p-4"><b className="block">{title}</b><small className="mt-1 block text-slate-500">{value}</small></div>; }
function statusName(s:string) { return ({PENDING:'Chờ xử lý',NEW:'Mới',CONTACTED:'Đã liên hệ',QUOTED:'Đã báo giá',WON:'Thành công',LOST:'Không tiếp tục',CONFIRMED:'Đã xác nhận',PROCESSING:'Đang chuẩn bị',SHIPPING:'Đang giao',COMPLETED:'Hoàn tất',CANCELLED:'Đã hủy',REQUESTED:'Mới nhận',ISSUED:'Đã phát hành',REJECTED:'Từ chối'} as Record<string,string>)[s] || s; }
