import { useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { api, unwrap } from '../api/client';

type Kind='services'|'videos'|'articles';
export default function AdminContentPage({kind}:{kind:Kind}) {
  const qc=useQueryClient(); const key=['admin-content',kind]; const endpoint=`/admin/content/${kind}`;
  const {data=[]}=useQuery({queryKey:key,queryFn:()=>api.get(endpoint).then(unwrap<any[]>)});
  const remove=async(id:number)=>{if(!window.confirm('Xóa nội dung này?'))return;await api.delete(`${endpoint}/${id}`);qc.invalidateQueries({queryKey:key});toast.success('Đã xóa nội dung');};
  const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const title=String(f.get('title'));const slug=String(f.get('slug')||title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));let payload:any;
    if(kind==='services')payload={title,slug,summary:f.get('summary'),phone:f.get('phone'),status:f.get('status')};
    if(kind==='articles')payload={title,slug,summary:f.get('summary'),content:f.get('content'),thumbnailUrl:f.get('image'),videoUrl:f.get('video'),author:'Văn Quân',publishedAt:new Date().toISOString().slice(0,10),status:f.get('status')};
    if(kind==='videos')payload={title,url:f.get('url'),platform:f.get('platform'),status:f.get('status')};
    await api.post(endpoint,payload);form.reset();qc.invalidateQueries({queryKey:key});qc.invalidateQueries({queryKey:['articles']});toast.success('Đã lưu nội dung');};
  const heading=kind==='services'?'Dịch vụ hỗ trợ':kind==='articles'?'Bài viết & kiến thức':'Thư viện video';
  return <><div className="mb-6"><p className="eyebrow">VĂN QUÂN · QUẢN TRỊ NỘI DUNG</p><h1 className="mt-2 text-3xl font-black text-navy">{heading}</h1><p className="mt-2 text-slate-500">{kind==='services'?'Quản lý dịch vụ hiển thị cho khách hàng.':kind==='articles'?'Tạo bài viết, lưu nháp hoặc xuất bản trực tiếp lên trang tin.':'Lưu đường dẫn video để gắn vào nội dung website.'}</p></div>
  <form onSubmit={create} className="admin-panel mb-6"><h2 className="mb-4 text-lg font-black">Tạo nội dung mới</h2><div className="grid gap-3 md:grid-cols-2"><input required name="title" className="field" placeholder="Tiêu đề"/><input name="slug" className="field" placeholder="Đường dẫn (slug, tự tạo nếu bỏ trống)"/>{kind==='services'?<><input name="summary" className="field md:col-span-2" placeholder="Mô tả ngắn"/><input name="phone" className="field" placeholder="Số điện thoại hỗ trợ"/></>:kind==='articles'?<><input name="summary" className="field md:col-span-2" placeholder="Tóm tắt bài viết"/><input name="image" className="field md:col-span-2" placeholder="URL ảnh bìa"/><input name="video" type="url" className="field md:col-span-2" placeholder="Link video YouTube / Vimeo (không bắt buộc)"/><textarea required name="content" className="field h-36 py-3 md:col-span-2" placeholder="Nội dung bài viết"/></>:<><input required name="url" type="url" className="field" placeholder="Link video YouTube / Vimeo"/><input name="platform" className="field" placeholder="Nền tảng / ghi chú"/></>}<select name="status" className="field"><option value="PUBLISHED">Xuất bản / đang hiển thị</option><option value="DRAFT">Bản nháp</option></select><button className="btn bg-red text-white">Lưu nội dung</button></div></form>
  <div className="admin-panel overflow-x-auto !p-0"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-navy text-white"><tr>{['Tiêu đề','Đường dẫn / loại','Mô tả / video','Trạng thái','Thao tác'].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody>{data.map((x:any)=><tr key={x.id} className="border-t border-line"><td className="px-5 py-4 font-bold">{x.title}</td><td className="px-5 py-4">{x.slug||x.platform||'—'}</td><td className="max-w-sm px-5 py-4">{kind==='articles'&&x.videoUrl?<a className="text-red underline" href={x.videoUrl} target="_blank" rel="noreferrer">Video đính kèm</a>:kind==='videos'?<a className="text-red underline" href={x.url} target="_blank" rel="noreferrer">Mở video</a>:x.summary}</td><td className="px-5 py-4">{x.status==='DRAFT'?'Bản nháp':'Đang hiển thị'}</td><td className="px-5 py-4"><button className="font-bold text-red" onClick={()=>remove(x.id)}>Xóa</button></td></tr>)}</tbody></table></div></>;
}
