import { ArrowRight, CheckCircle2, ChevronRight, Factory, Gauge, Headphones, PackageCheck, Search, Settings, ShieldCheck, Wrench, Wind, Droplets, Cog, CircleDollarSign } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';

const categories = [
  ['Máy nén khí trục vít', '85 sản phẩm', Gauge], ['Phụ tùng máy nén khí', '586 sản phẩm', Cog], ['Linh kiện máy nén khí', '237 sản phẩm', PackageCheck], ['Máy tạo khí Nitơ', '12 sản phẩm', Factory], ['Máy sấy khí nén', '22 sản phẩm', Wind], ['Lọc đường ống khí nén', '25 sản phẩm', ShieldCheck], ['Bình tích áp', '13 sản phẩm', Factory], ['Dầu máy nén khí', '11 sản phẩm', Droplets], ['Lọc Donaldson', '573 sản phẩm', Settings], ['Máy nén khí piston', '8 sản phẩm', Gauge], ['Dịch vụ kỹ thuật', '10 dịch vụ', Wrench],
] as const;
const products = [
  ['Máy nén khí trục vít Kaishan BMVF90', 'KAISHAN · BIẾN TẦN', 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=84'],
  ['Máy nén khí Kaishan BMVF55G', 'KAISHAN · TRỤC VÍT', 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=84'],
  ['Máy nén khí LG110-8GA công nghiệp', 'LG · HIỆU SUẤT CAO', 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=84'],
  ['Máy nén khí piston LG-1.2/8A', 'LG · PISTON', 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=84'],
  ['Máy nén khí Sullair LS-20S', 'SULLAIR · TRỤC VÍT', 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=84'],
  ['Máy sấy khí tác nhân lạnh Lode Star', 'LODE STAR · XỬ LÝ KHÍ', 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=84'],
  ['Bộ lọc đường ống khí nén 3 cấp', 'JMEC · LỌC KHÍ', 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=84'],
  ['Bình tích áp khí nén 500 lít', 'THIẾT BỊ PHỤ TRỢ', 'https://images.unsplash.com/photo-1565439396-0ef56ea0b21e?auto=format&fit=crop&w=900&q=84'],
] as const;

export default function HomePage() {
  const [q, setQ] = useState(''); const nav = useNavigate();
  const search = (e: FormEvent) => { e.preventDefault(); nav(`/products?search=${encodeURIComponent(q)}`); };
  return <>
    <section className="hero-industrial relative overflow-hidden text-white"><div className="hero-grid container relative z-10 grid min-h-[590px] items-center gap-10 py-20 lg:grid-cols-[1.15fr_.85fr]"><div className="max-w-3xl animate-rise"><p className="eyebrow text-yellow">ĐỐI TÁC KHÍ NÉN CÔNG NGHIỆP · TỪ 2010</p><h1 className="mt-5 text-4xl font-black leading-[1.05] tracking-tight sm:text-6xl">GIẢI PHÁP KHÍ NÉN<br/><span className="text-yellow">CHO NHÀ MÁY HIỆN ĐẠI</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-100">Thiết bị chính hãng, tư vấn đúng tải và dịch vụ kỹ thuật đồng hành trong suốt vòng đời hệ thống.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/products" className="btn bg-red text-white">Khám phá sản phẩm <ArrowRight size={18}/></Link><a href="tel:0946678168" className="btn border border-white/50 text-white">Tư vấn: 0946 678 168</a></div><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 text-sm font-bold text-white"><span className="flex items-center gap-2"><CheckCircle2 size={18} className="text-yellow"/>Sản phẩm đa dạng</span><span className="flex items-center gap-2"><CheckCircle2 size={18} className="text-yellow"/>Bảo hành rõ ràng</span><span className="flex items-center gap-2"><CheckCircle2 size={18} className="text-yellow"/>Kỹ thuật 24/7</span></div></div><div className="hidden lg:block animate-rise delay-150"><div className="hero-panel"><span className="text-sm font-extrabold uppercase tracking-widest text-yellow">Văn Quân · Đồng hành kỹ thuật</span><p className="mt-4 text-2xl font-black leading-snug">Đúng thiết bị. Đúng cấu hình. Vận hành bền bỉ.</p><div className="mt-6 grid grid-cols-3 gap-3 border-t border-white/20 pt-6 text-center"><Stat value="16+" label="Năm kinh nghiệm"/><Stat value="500+" label="Khách hàng"/><Stat value="24/7" label="Hỗ trợ kỹ thuật"/></div></div></div></div></section>
    <section className="relative z-20 -mt-8"><form onSubmit={search} className="container flex rounded bg-white p-3 shadow-2xl"><input className="field h-14 rounded-r-none border-0 bg-slate-50" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Tìm máy nén khí, phụ tùng, dầu máy..."/><button className="btn h-14 rounded-l-none bg-red text-white"><Search size={20}/><span className="hidden sm:inline">Tìm sản phẩm</span></button></form></section>
    <section className="section"><div className="container"><SectionTitle small="DANH MỤC SẢN PHẨM" title="Tìm nhanh theo nhu cầu nhà máy"/><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map(([name, count, Icon], i) => <Link key={name} to={`/products?search=${encodeURIComponent(name)}`} style={{ animationDelay: `${i * 45}ms` }} className="category-card group animate-rise"><span className="grid h-14 w-14 shrink-0 place-items-center bg-navy text-yellow"><Icon size={26}/></span><span className="min-w-0"><b className="block text-lg group-hover:text-red">{name}</b><small className="mt-1 block text-slate-500">{count}</small></span><ChevronRight className="ml-auto shrink-0 text-slate-300 group-hover:text-red" size={20}/></Link>)}</div></div></section>
    <section className="section bg-surface"><div className="container"><div className="flex flex-wrap items-end justify-between gap-4"><SectionTitle small="SẢN PHẨM NỔI BẬT" title="Thiết bị được nhà máy tin chọn"/><Link to="/products" className="font-extrabold text-red">Xem toàn bộ catalogue <ArrowRight className="inline" size={16}/></Link></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map(([name, type, image], i) => <article key={name} style={{ animationDelay: `${i * 60}ms` }} className="product-tile group animate-rise"><Link to="/products"><div className="aspect-[4/3] overflow-hidden bg-white"><img src={image} alt={name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" loading="lazy"/></div><div className="p-5"><small className="font-extrabold tracking-wider text-red">{type}</small><h3 className="mt-2 min-h-14 text-lg font-black leading-snug">{name}</h3><div className="mt-4 flex items-center justify-between border-t border-line pt-4 text-sm font-extrabold"><span className="text-slate-600">Liên hệ báo giá</span><ArrowRight className="text-red" size={17}/></div></div></Link></article>)}</div></div></section>
    <section className="section"><div className="container grid items-center gap-12 lg:grid-cols-2"><div className="relative"><img className="h-[420px] w-full object-cover" src="https://maynenkhibaotin.com/ckfinder/userfiles/images/bao-duong-may-nen-khi.jpg" alt="Kỹ thuật viên bảo dưỡng máy nén khí"/><div className="absolute bottom-0 right-0 max-w-xs bg-red p-6 text-white"><b className="text-2xl">Dịch vụ tận nơi</b><p className="mt-2 text-sm leading-6">Khảo sát, bảo dưỡng và xử lý sự cố tại nhà máy.</p></div></div><div><SectionTitle small="DỊCH VỤ KỸ THUẬT" title="Giữ hệ thống ổn định, tiết kiệm năng lượng"/><p className="mt-5 leading-8 text-slate-600">Đội ngũ Văn Quân đồng hành từ bảo trì định kỳ đến đại tu, sửa chữa và tối ưu phòng máy cho nhiều thương hiệu thiết bị.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><Service icon={Settings} title="Bảo dưỡng định kỳ"/><Service icon={Wrench} title="Sửa chữa & đại tu"/><Service icon={Factory} title="Lắp đặt hệ thống"/><Service icon={Headphones} title="Hỗ trợ khẩn cấp 24/7"/></div><Link to="/services/bao-duong" className="btn mt-8 bg-navy text-white">Khám phá dịch vụ <ArrowRight size={18}/></Link></div></div></section>
    <section className="bg-navy py-14 text-white"><div className="container grid gap-8 lg:grid-cols-[1fr_auto]"><div><p className="eyebrow text-yellow">VĂN QUÂN INDUSTRIAL</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Năng lực kỹ thuật làm nên khác biệt</h2><p className="mt-4 max-w-3xl leading-8 text-slate-200">Từ lựa chọn thiết bị, thiết kế phòng máy đến vận hành và bảo dưỡng dài hạn — một đầu mối xuyên suốt cho hệ thống khí nén của bạn.</p></div><div className="grid grid-cols-2 gap-px self-stretch bg-white/20"><StatBox value="100%" label="Tư vấn theo nhu cầu"/><StatBox value="24/7" label="Sẵn sàng hỗ trợ"/></div></div></section>
    <section className="bg-yellow py-10"><div className="container flex flex-col items-start justify-between gap-5 md:flex-row md:items-center"><div><h2 className="text-2xl font-black text-navy">Cần tư vấn giải pháp khí nén?</h2><p className="mt-1 text-navy/80">Trao đổi trực tiếp với kỹ sư để chọn cấu hình phù hợp.</p></div><a href="tel:0946678168" className="btn bg-red text-white"><CircleDollarSign size={18}/>0946 678 168</a></div></section>
  </>;
}
function SectionTitle({ small, title }: { small: string; title: string }) { return <div><p className="eyebrow">{small}</p><h2 className="title mt-2 max-w-3xl">{title}</h2></div>; }
function Stat({ value, label }: { value: string; label: string }) { return <div><b className="text-2xl text-yellow">{value}</b><small className="mt-1 block text-slate-200">{label}</small></div>; }
function Service({ icon: Icon, title }: { icon: typeof Settings; title: string }) { return <div className="flex items-center gap-3 border border-line p-4 font-extrabold"><span className="grid h-11 w-11 place-items-center bg-red/10 text-red"><Icon size={21}/></span>{title}</div>; }
function StatBox({ value, label }: { value: string; label: string }) { return <div className="min-w-44 bg-navy p-6 text-center"><b className="text-3xl text-yellow">{value}</b><small className="mt-2 block text-slate-200">{label}</small></div>; }
