import axios, { type AxiosAdapter, type AxiosResponse } from 'axios';

const products = [
  { id: 1, name: 'Máy nén khí trục vít Sullair LS-20S', slug: 'may-nen-khi-sullair-ls-20s', sku: 'SUL-LS20', shortDescription: 'Máy nén khí trục vít có dầu, hoạt động ổn định cho dây chuyền sản xuất liên tục.', description: '<p>Dòng máy trục vít hiệu suất cao, thiết kế dễ bảo dưỡng, phù hợp nhà máy vừa và lớn.</p>', categoryId: 1, category: { id: 1, name: 'Máy nén khí', slug: 'may-nen-khi' }, brand: { id: 1, name: 'Sullair', slug: 'sullair' }, price: 185000000, salePrice: 176000000, priceType: 'FIXED', stockQuantity: 8, unit: 'máy', status: 'ACTIVE', featured: true, bestSelling: true, newProduct: true, thumbnailUrl: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=84', warranty: '24 tháng', origin: 'Hoa Kỳ', manufacturer: 'Sullair', specifications: [{ id: 1, name: 'Công suất', value: '15 kW / 20 HP' }, { id: 2, name: 'Lưu lượng', value: '2.3 m³/phút' }, { id: 3, name: 'Áp suất', value: '8 bar' }] },
  { id: 2, name: 'Máy nén khí trục vít Hitachi 22kW', slug: 'may-nen-khi-hitachi-22kw', sku: 'HIT-22KW', shortDescription: 'Thiết kế bền bỉ, vận hành êm và tiết kiệm năng lượng.', description: '<p>Giải pháp khí nén Hitachi chính hãng cho nhà máy sản xuất.</p>', categoryId: 1, category: { id: 1, name: 'Máy nén khí', slug: 'may-nen-khi' }, brand: { id: 2, name: 'Hitachi', slug: 'hitachi' }, price: 228000000, priceType: 'QUOTE', stockQuantity: 5, unit: 'máy', status: 'ACTIVE', featured: true, bestSelling: true, newProduct: false, thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=84', warranty: '24 tháng', origin: 'Nhật Bản', manufacturer: 'Hitachi', specifications: [{ id: 4, name: 'Công suất', value: '22 kW' }, { id: 5, name: 'Áp suất', value: '8 bar' }] },
  { id: 3, name: 'Máy sấy khí Lode Star 5.5 m³/phút', slug: 'may-say-khi-lode-star-55', sku: 'LDS-055', shortDescription: 'Tách ẩm hiệu quả, bảo vệ hệ thống đường ống và thiết bị đầu cuối.', description: '<p>Máy sấy lạnh công nghiệp cho khí nén sạch và khô.</p>', categoryId: 2, category: { id: 2, name: 'Máy sấy khí', slug: 'may-say-khi' }, brand: { id: 3, name: 'Lode Star', slug: 'lode-star' }, price: 42500000, priceType: 'FIXED', stockQuantity: 12, unit: 'máy', status: 'ACTIVE', featured: true, bestSelling: false, newProduct: true, thumbnailUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=84', warranty: '12 tháng', origin: 'Đài Loan', manufacturer: 'Lode Star', specifications: [{ id: 6, name: 'Lưu lượng', value: '5.5 m³/phút' }, { id: 7, name: 'Điểm sương', value: '2–10°C' }] },
  { id: 4, name: 'Lọc đường ống Lode Star G420', slug: 'loc-duong-ong-lode-star-g420', sku: 'G420', shortDescription: 'Lọc bụi, dầu và nước trong khí nén, lưu lượng lớn cho hệ thống công nghiệp.', description: '<p>Bộ lọc đường ống nhiều cấp, bảo vệ thiết bị và đảm bảo chất lượng khí.</p>', categoryId: 3, category: { id: 3, name: 'Lọc đường ống khí nén', slug: 'loc-duong-ong' }, brand: { id: 3, name: 'Lode Star', slug: 'lode-star' }, priceType: 'CONTACT', stockQuantity: 7, unit: 'bộ', status: 'ACTIVE', featured: true, bestSelling: true, newProduct: false, thumbnailUrl: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=84', warranty: '12 tháng', origin: 'Đài Loan', manufacturer: 'JMEC', specifications: [{ id: 8, name: 'Lưu lượng', value: '42 m³/phút' }, { id: 9, name: 'Áp lực', value: '10 bar' }, { id: 10, name: 'Cấp lọc', value: 'Q, P, H, C, X' }] },
  { id: 5, name: 'Bình tích áp thép 500 lít', slug: 'binh-tich-ap-500-lit', sku: 'BT-500L', shortDescription: 'Bình chứa khí nén dung tích lớn, kết cấu thép sơn phủ chống ăn mòn.', description: '<p>Bình tích áp giúp ổn định áp suất và giảm tải máy nén khí.</p>', categoryId: 4, category: { id: 4, name: 'Bình tích áp', slug: 'binh-tich-ap' }, brand: { id: 4, name: 'Bảo Tín', slug: 'bao-tin' }, price: 19800000, priceType: 'FIXED', stockQuantity: 6, unit: 'bình', status: 'ACTIVE', featured: false, bestSelling: true, newProduct: false, thumbnailUrl: 'https://images.unsplash.com/photo-1565439396-0ef56ea0b21e?auto=format&fit=crop&w=900&q=84', warranty: '12 tháng', origin: 'Việt Nam', manufacturer: 'Bảo Tín', specifications: [{ id: 11, name: 'Dung tích', value: '500 lít' }, { id: 12, name: 'Áp suất thiết kế', value: '10 bar' }] },
  { id: 6, name: 'Dầu máy nén khí Idemitsu VG32', slug: 'dau-may-nen-khi-idemitsu-vg32', sku: 'ID-VG32-20L', shortDescription: 'Dầu máy nén khí chính hãng, giúp bôi trơn và kéo dài tuổi thọ đầu nén.', description: '<p>Dầu Idemitsu VG32 cho các dòng máy nén khí trục vít tương thích.</p>', categoryId: 5, category: { id: 5, name: 'Dầu máy nén khí', slug: 'dau-may-nen-khi' }, brand: { id: 5, name: 'Idemitsu', slug: 'idemitsu' }, price: 2850000, priceType: 'FIXED', stockQuantity: 24, unit: 'can', status: 'ACTIVE', featured: false, bestSelling: true, newProduct: true, thumbnailUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=84', warranty: 'Chính hãng', origin: 'Nhật Bản', manufacturer: 'Idemitsu', specifications: [{ id: 13, name: 'Dung tích', value: '20 lít' }, { id: 14, name: 'Độ nhớt', value: 'VG32' }] },
  { id: 7, name: 'Lõi lọc dầu máy nén khí Hitachi', slug: 'loi-loc-dau-hitachi', sku: 'HIT-OIL-01', shortDescription: 'Phụ tùng thay thế chất lượng cao cho bảo dưỡng định kỳ.', description: '<p>Lõi lọc tương thích các dòng máy nén khí Hitachi.</p>', categoryId: 6, category: { id: 6, name: 'Phụ tùng máy nén khí', slug: 'phu-tung' }, brand: { id: 2, name: 'Hitachi', slug: 'hitachi' }, price: 1250000, priceType: 'FIXED', stockQuantity: 30, unit: 'cái', status: 'ACTIVE', featured: false, bestSelling: false, newProduct: false, thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=84', warranty: '3 tháng', origin: 'Nhật Bản', manufacturer: 'Hitachi', specifications: [{ id: 15, name: 'Loại lọc', value: 'Lọc dầu' }] },
  { id: 8, name: 'Máy nén khí không dầu Sullair GS', slug: 'may-nen-khi-khong-dau-sullair-gs', sku: 'SUL-GS-30', shortDescription: 'Khí nén sạch cho ngành thực phẩm, dược phẩm và điện tử.', description: '<p>Máy nén khí không dầu hiệu suất cao, phù hợp môi trường yêu cầu khí sạch.</p>', categoryId: 1, category: { id: 1, name: 'Máy nén khí', slug: 'may-nen-khi' }, brand: { id: 1, name: 'Sullair', slug: 'sullair' }, priceType: 'QUOTE', stockQuantity: 3, unit: 'máy', status: 'ACTIVE', featured: true, bestSelling: false, newProduct: true, thumbnailUrl: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=84', warranty: '24 tháng', origin: 'Hoa Kỳ', manufacturer: 'Sullair', specifications: [{ id: 16, name: 'Công suất', value: '30 kW' }, { id: 17, name: 'Khí đầu ra', value: 'Không dầu' }] },
  { id: 9, name: 'Máy tạo khí Nitơ công nghiệp', slug: 'may-tao-khi-nito-cong-nghiep', sku: 'BT-N2-01', shortDescription: 'Hệ thống tạo Nitơ tại chỗ cho bao bì, điện tử và quy trình công nghiệp.', description: '<p>Giải pháp cấp khí Nitơ ổn định, cấu hình theo độ tinh khiết và lưu lượng yêu cầu.</p>', categoryId: 7, category: { id: 7, name: 'Máy tạo khí Nitơ', slug: 'may-tao-khi-nito' }, brand: { id: 4, name: 'Bảo Tín', slug: 'bao-tin' }, priceType: 'QUOTE', stockQuantity: 2, unit: 'hệ thống', status: 'ACTIVE', featured: false, bestSelling: false, newProduct: true, thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=84', warranty: '12 tháng', origin: 'Theo cấu hình', manufacturer: 'Bảo Tín', specifications: [{ id: 18, name: 'Độ tinh khiết', value: 'Theo nhu cầu' }, { id: 19, name: 'Vận hành', value: 'Tự động' }] },
  { id: 10, name: 'Máy bơm chân không công nghiệp', slug: 'may-bom-chan-khong-cong-nghiep', sku: 'BT-VAC-01', shortDescription: 'Bơm chân không cho các dây chuyền đóng gói và sản xuất.', description: '<p>Tư vấn model theo lưu lượng hút, độ chân không và chu kỳ làm việc.</p>', categoryId: 8, category: { id: 8, name: 'Máy bơm chân không', slug: 'bom-chan-khong' }, brand: { id: 4, name: 'Bảo Tín', slug: 'bao-tin' }, priceType: 'CONTACT', stockQuantity: 4, unit: 'máy', status: 'ACTIVE', featured: false, bestSelling: false, newProduct: false, thumbnailUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=84', warranty: '12 tháng', origin: 'Liên hệ', manufacturer: 'Bảo Tín', specifications: [{ id: 20, name: 'Ứng dụng', value: 'Đóng gói, sản xuất' }] },
];
const categories = [
  { id: 1, name: 'Máy nén khí', slug: 'may-nen-khi', parentId: null }, { id: 11, name: 'Máy nén khí trục vít', slug: 'may-nen-khi-truc-vit', parentId: 1 }, { id: 12, name: 'Máy nén khí piston', slug: 'may-nen-khi-piston', parentId: 1 }, { id: 13, name: 'Máy nén khí không dầu', slug: 'may-nen-khi-khong-dau', parentId: 1 },
  { id: 2, name: 'Máy sấy khí', slug: 'may-say-khi', parentId: null }, { id: 21, name: 'Máy sấy khí Sullair', slug: 'may-say-khi-sullair', parentId: 2 }, { id: 22, name: 'Máy sấy khí Lode Star', slug: 'may-say-khi-lode-star', parentId: 2 },
  { id: 3, name: 'Lọc đường ống khí nén', slug: 'loc-duong-ong', parentId: null }, { id: 31, name: 'Lọc đường ống Sullair', slug: 'loc-duong-ong-sullair', parentId: 3 }, { id: 32, name: 'Lọc đường ống JMEC', slug: 'loc-duong-ong-jmec', parentId: 3 }, { id: 4, name: 'Bình tích áp', slug: 'binh-tich-ap', parentId: null },
  { id: 5, name: 'Dầu máy nén khí', slug: 'dau-may-nen-khi', parentId: null }, { id: 6, name: 'Phụ tùng máy nén khí', slug: 'phu-tung', parentId: null }, { id: 7, name: 'Máy tạo khí Nitơ', slug: 'may-tao-khi-nito', parentId: null }, { id: 8, name: 'Máy bơm chân không', slug: 'bom-chan-khong', parentId: null },
];
const brands = [{ id: 1, name: 'Sullair', slug: 'sullair' }, { id: 2, name: 'Hitachi', slug: 'hitachi' }, { id: 3, name: 'Lode Star', slug: 'lode-star' }, { id: 4, name: 'Bảo Tín', slug: 'bao-tin' }, { id: 5, name: 'Idemitsu', slug: 'idemitsu' }];
const extraCatalog = [
  ['Máy nén khí Kaishan BMVF90 biến tần',1,'Kaishan'],['Máy nén khí Kaishan BMVF55G trục vít',1,'Kaishan'],['Máy nén khí LG110-8GA công suất lớn',1,'LG'],['Máy nén khí piston LG-1.2/8A',1,'LG'],['Máy nén khí diesel Sullair di động',1,'Sullair'],['Máy sấy khí nén tác nhân lạnh 5.5 m³/phút',2,'Lode Star'],['Máy sấy khí hấp thụ công nghiệp',2,'JMEC'],['Lọc đường ống Donaldson G420',3,'Donaldson'],['Lọc đường ống Donaldson G280',3,'Donaldson'],['Bình tích áp đứng 1000 lít',4,'Văn Quân'],['Dầu máy nén khí Idemitsu VG32 20L',5,'Idemitsu'],['Dầu máy nén khí Sullair 24KT',5,'Sullair'],['Lõi lọc dầu máy nén khí Hitachi',6,'Hitachi'],['Lõi lọc tách dầu Sullair',6,'Sullair'],['Lọc gió máy nén khí Kobelco',6,'Kobelco'],['Máy tạo khí Nitơ PSA công nghiệp',7,'Văn Quân'],['Bơm chân không vòng dầu công nghiệp',8,'Văn Quân'],['Lọc Donaldson thay thế cho máy nén khí',6,'Donaldson'],['Bộ lọc khí nén chính xác 3 cấp',3,'JMEC'],['Phụ tùng van hút máy nén khí trục vít',6,'Sullair'],
];
const catalogProducts = [...products, ...extraCatalog.map(([name, categoryId, brandName], i) => {
  const category = categories.find((c) => c.id === categoryId) || categories[0]!;
  const brand = brands.find((b) => b.name === brandName) || brands[0]!;
  const image = products[i % products.length]!.thumbnailUrl;
  return { ...products[i % products.length]!, id: products.length + i + 1, name, slug: String(name).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''), sku: `VQ-${String(i+1).padStart(3,'0')}`, categoryId: category.id, category, brand, manufacturer: brand.name, priceType: 'QUOTE', price: undefined, salePrice: undefined, stockQuantity: 2 + i % 18, featured: i < 8, thumbnailUrl: image, shortDescription: `${name} - tư vấn cấu hình, lưu lượng và áp suất theo nhu cầu vận hành thực tế.` };
})];
const articles = [
  { id: 1, slug: 'bao-duong-may-nen-khi-hitachi', title: 'Bảo dưỡng máy nén khí Hitachi: quy trình và lịch định kỳ', summary: 'Hướng dẫn kiểm tra lọc dầu, lọc gió, lọc tách và dầu máy để hệ thống hoạt động ổn định.', author: 'Kỹ thuật Bảo Tín', publishedAt: '2026-09-18', thumbnailUrl: 'https://maynenkhibaotin.com/ckfinder/userfiles/images/bao-duong-may-nen-khi.jpg', content: 'Bảo dưỡng đúng lịch giúp máy vận hành ổn định, tiết kiệm năng lượng và hạn chế dừng máy đột xuất.' },
  { id: 2, slug: 'lap-dat-he-thong-khi-nen', title: 'Sơ đồ lắp đặt hệ thống khí nén trong nhà xưởng', summary: 'Vị trí máy nén, bình tích áp, máy sấy và bộ lọc ảnh hưởng trực tiếp đến chất lượng khí.', author: 'Bảo Tín Industrial', publishedAt: '2026-08-26', thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=84', content: 'Bình tích áp thường đặt sau máy nén; máy sấy và lọc được lựa chọn theo lưu lượng, áp suất và tiêu chuẩn chất lượng khí.' },
  { id: 3, slug: 'chon-may-nen-khi-truc-vit', title: 'Cách chọn máy nén khí trục vít phù hợp công suất nhà máy', summary: 'Các yếu tố cần tính đến: lưu lượng, áp suất, nhu cầu dùng đồng thời và khả năng mở rộng.', author: 'Chuyên gia khí nén', publishedAt: '2026-07-11', thumbnailUrl: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=84', content: 'Khảo sát biểu đồ sử dụng khí và mức áp suất thực tế là bước đầu để chọn đúng công suất.' },
];
let nextId = 9;
const readProducts = () => JSON.parse(localStorage.getItem('mock_products') || 'null') || catalogProducts;
const readCategories = () => JSON.parse(localStorage.getItem('mock_categories') || 'null') || categories;
const readOrders = () => { let list = JSON.parse(localStorage.getItem('mock_orders') || 'null'); if (!list) { list = seedOrders(); localStorage.setItem('mock_orders', JSON.stringify(list)); } return list; };
const readUserArticles = () => JSON.parse(localStorage.getItem('mock_user_articles') || '[]');
const readArticleStatuses = () => JSON.parse(localStorage.getItem('mock_article_statuses') || '{}');
const readQuotes = () => { let list=JSON.parse(localStorage.getItem('mock_quotes')||'null');if(!list){list=[{id:101,name:'Nguyễn Minh Tuấn',company:'Cơ khí Minh Phát',productName:'Máy nén khí Sullair LS-20S',phone:'0903 222 818',email:'tuan@minhphat.vn',status:'NEW'},{id:102,name:'Lê Thu Hà',company:'Thực phẩm An Việt',productName:'Máy nén khí không dầu Sullair',phone:'0912 333 181',status:'CONTACTED'}];localStorage.setItem('mock_quotes',JSON.stringify(list));}return list; };
const readVatRequests = () => { let list=JSON.parse(localStorage.getItem('mock_vats')||'null');if(!list){list=[{id:201,orderCode:'BT-2026-0081',companyName:'Công ty TNHH Cơ khí Minh Phát',taxCode:'0109988776',invoiceEmail:'ketoan@minhphat.vn',status:'REQUESTED'}];localStorage.setItem('mock_vats',JSON.stringify(list));}return list; };
const readAddresses = () => { let list=JSON.parse(localStorage.getItem('mock_addresses')||'null');if(!list){list=[{id:301,recipientName:'Nguyễn Minh Tuấn',phone:'0903 222 818',addressLine:'Lô B2, KCN Thăng Long',wardCode:'P2',wardName:'Đông Anh',provinceCode:'HN',provinceName:'Hà Nội',isDefault:true}];localStorage.setItem('mock_addresses',JSON.stringify(list));}return list; };
const seedOrders = () => { const sample=products[0]!;const price=sample.price||0;return [{ orderCode: 'BT-2026-0081', customerName: 'Nguyễn Minh Tuấn', customerPhone: '0903 222 818', customerEmail: 'tuan@minhphat.vn', shippingFullAddress: 'Lô B2, KCN Thăng Long, Đông Anh, Hà Nội', status: 'PROCESSING', items: [{ productId: 1, productName: sample.name, sku: sample.sku, thumbnailUrl: sample.thumbnailUrl, unitPrice: price, quantity: 1, subtotal: price }], subtotal: price, discount: 9000000, shippingFee: 0, vatAmount: 0, grandTotal: price - 9000000, payment: { method: 'BANK_TRANSFER', status: 'PENDING', amount: price, mock: true }, vat: { companyName: 'Công ty TNHH Cơ khí Minh Phát', status: 'REQUESTED' }, createdAt: '2026-10-06T09:30:00' }]; };
const getData = (value: unknown): AxiosResponse => ({ data: { data: value }, status: 200, statusText: 'OK', headers: {}, config: {} as never });
const paramsOf = (config: { params?: Record<string, unknown>; url?: string }) => config.params || Object.fromEntries(new URLSearchParams((config.url || '').split('?')[1] || ''));
const mockAdapter: AxiosAdapter = async (config) => {
  await new Promise((resolve) => setTimeout(resolve, 110));
  const method = (config.method || 'get').toLowerCase(); const path = (config.url || '').replace(/^https?:\/\/[^/]+/, '').split('?')[0].replace(/^.*\/api\/v1/, '') || '/'; const params = paramsOf(config); let body: any = config.data;
  if (typeof body === 'string') { try { body = JSON.parse(body); } catch { body = {}; } }
  let result: unknown = null;
  if (path === '/categories' || path === '/admin/categories' && method === 'get') result = readCategories();
  else if (path === '/admin/categories' && method === 'post') { const list = readCategories(); const created = { ...body, id: nextId++, parentId: body.parentId || null }; list.push(created); localStorage.setItem('mock_categories', JSON.stringify(list)); result = created; }
  else if (path === '/brands') result = brands;
  else if (path === '/products' && method === 'get') {
    let list = [...readProducts()]; const query = String(params.search || '').toLowerCase();
    if (query) { const queryCat = readCategories().find((c: { name: string; slug: string }) => c.name.toLowerCase() === query || c.slug === query); list = list.filter((p) => `${p.name} ${p.sku} ${p.category.name} ${p.brand.name}`.toLowerCase().includes(query) || (queryCat && (p.categoryId === queryCat.id || p.categoryId === queryCat.parentId))); }
    if (params.category) { const cat = readCategories().find((c: { id: number; slug: string }) => String(c.id) === String(params.category) || c.slug === params.category); list = list.filter((p) => p.categoryId === Number(params.category) || p.category.slug === params.category || (cat?.parentId && p.categoryId === cat.parentId)); }
    if (params.brand) list = list.filter((p) => String(p.brand.id) === String(params.brand) || p.brand.slug === params.brand);
    if (params.featured === 'true') list = list.filter((p) => p.featured);
    if (params.sort === 'price-asc') list.sort((a, b) => (a.price || 0) - (b.price || 0)); if (params.sort === 'price-desc') list.sort((a, b) => (b.price || 0) - (a.price || 0));
    result = { content: list, totalElements: list.length, totalPages: 1, number: 0, size: list.length };
  } else if (path.startsWith('/products/') && method === 'get') result = readProducts().find((p: { slug: string }) => p.slug === path.split('/').pop()) || null;
  else if (path === '/articles') result = [...articles,...JSON.parse(localStorage.getItem('mock_content_articles') || '[]').filter((a:{status:string})=>a.status==='PUBLISHED'),...readUserArticles().filter((a:{status:string})=>a.status==='PUBLISHED')];
  else if (path.startsWith('/articles/')) result = [...articles,...JSON.parse(localStorage.getItem('mock_content_articles') || '[]'),...readUserArticles()].find((a) => a.slug === path.split('/').pop()) || articles[0];
  else if (path === '/auth/login' || path === '/auth/register') { const email = body.email || 'khachhang@example.com'; result = { accessToken: 'mock-token-' + Date.now(), role: email.toLowerCase().startsWith('admin') ? 'ADMIN' : 'USER', email, fullName: body.fullName || 'Khách hàng Bảo Tín', phone: body.phone || '0983 755 949' }; }
  else if (path === '/admin/dashboard') result = { products: products.length, users: 128, orders: 36, pendingOrders: 5, quotes: 12, revenue: 1285000000 };
  else if (path === '/admin/products' && method === 'get') result = readProducts();
  else if (path === '/admin/products' && method === 'post') { const list = readProducts(); const created = { ...body, id: nextId++, category: readCategories().find((c: { id: number }) => c.id === Number(body.categoryId)) || categories[0], brand: brands[0], specifications: [], createdAt: new Date().toISOString() }; list.unshift(created); localStorage.setItem('mock_products', JSON.stringify(list)); result = created; }
  else if (path.startsWith('/admin/products/') && method === 'delete') { const id=Number(path.split('/').pop());const list=readProducts().filter((p:{id:number})=>p.id!==id);localStorage.setItem('mock_products',JSON.stringify(list));result=null; }
  else if (path === '/admin/orders' || path === '/user/orders') result = readOrders();
  else if (path === '/admin/quotes') result = readQuotes();
  else if (path === '/admin/vat-invoices') result = readVatRequests();
  else if (path === '/admin/articles') { const statuses=readArticleStatuses();result = [...JSON.parse(localStorage.getItem('mock_content_articles') || '[]'), ...readUserArticles().filter((a: { status: string }) => a.status !== 'DRAFT'), ...articles.map((a) => ({ ...a, status: statuses[a.id]||'PUBLISHED' }))]; }
  else if (path === '/admin/content/articles' && method === 'get') result = JSON.parse(localStorage.getItem('mock_content_articles') || '[]');
  else if (path === '/admin/content/articles' && method === 'post') { const list=JSON.parse(localStorage.getItem('mock_content_articles')||'[]');const item={...body,id:nextId++,author:'Văn Quân',createdAt:new Date().toISOString()};list.unshift(item);localStorage.setItem('mock_content_articles',JSON.stringify(list));result=item; }
  else if (path.startsWith('/admin/content/articles/') && method === 'put') { const id=Number(path.split('/').pop());const list=JSON.parse(localStorage.getItem('mock_content_articles')||'[]');const at=list.findIndex((a:{id:number})=>a.id===id);if(at>=0)list[at]={...list[at],...body};localStorage.setItem('mock_content_articles',JSON.stringify(list));result=list[at]; }
  else if (path.startsWith('/admin/content/articles/') && method === 'delete') { const id=Number(path.split('/').pop());const list=JSON.parse(localStorage.getItem('mock_content_articles')||'[]').filter((a:{id:number})=>a.id!==id);localStorage.setItem('mock_content_articles',JSON.stringify(list));result=null; }
  else if (path === '/admin/content/services' && method === 'get') result = JSON.parse(localStorage.getItem('mock_content_services') || 'null') || [{id:1,title:'Bảo dưỡng máy nén khí',slug:'bao-duong',summary:'Bảo trì theo giờ chạy, thay vật tư và kiểm tra hệ thống.',status:'PUBLISHED',phone:'0946 678 168'},{id:2,title:'Sửa chữa & đại tu',slug:'sua-chua',summary:'Chẩn đoán sự cố và phục hồi thiết bị tại nhà máy.',status:'PUBLISHED',phone:'0946 678 168'},{id:3,title:'Lắp đặt hệ thống khí nén',slug:'lap-dat',summary:'Khảo sát, thiết kế và bàn giao hệ thống đồng bộ.',status:'PUBLISHED',phone:'0946 678 168'},{id:4,title:'Cho thuê máy nén khí',slug:'cho-thue',summary:'Bổ sung nguồn khí tạm thời khi bảo trì hoặc mở rộng.',status:'PUBLISHED',phone:'0946 678 168'}];
  else if (path === '/admin/content/services' && method === 'post') { const list=JSON.parse(localStorage.getItem('mock_content_services')||'null')||[];const item={...body,id:nextId++};list.unshift(item);localStorage.setItem('mock_content_services',JSON.stringify(list));result=item; }
  else if (path.startsWith('/admin/content/services/') && method === 'put') { const id=Number(path.split('/').pop());const list=JSON.parse(localStorage.getItem('mock_content_services')||'[]');const at=list.findIndex((a:{id:number})=>a.id===id);if(at>=0)list[at]={...list[at],...body};localStorage.setItem('mock_content_services',JSON.stringify(list));result=list[at]; }
  else if (path.startsWith('/admin/content/services/') && method === 'delete') { const id=Number(path.split('/').pop());const list=JSON.parse(localStorage.getItem('mock_content_services')||'[]').filter((a:{id:number})=>a.id!==id);localStorage.setItem('mock_content_services',JSON.stringify(list));result=null; }
  else if (path === '/admin/content/videos' && method === 'get') result = JSON.parse(localStorage.getItem('mock_content_videos') || '[]');
  else if (path === '/admin/content/videos' && method === 'post') { const list=JSON.parse(localStorage.getItem('mock_content_videos')||'[]');const item={...body,id:nextId++,createdAt:new Date().toISOString()};list.unshift(item);localStorage.setItem('mock_content_videos',JSON.stringify(list));result=item; }
  else if (path.startsWith('/admin/content/videos/') && method === 'delete') { const id=Number(path.split('/').pop());const list=JSON.parse(localStorage.getItem('mock_content_videos')||'[]').filter((a:{id:number})=>a.id!==id);localStorage.setItem('mock_content_videos',JSON.stringify(list));result=null; }
  else if (path === '/user/articles' && method === 'get') result = readUserArticles();
  else if (path === '/user/articles' && method === 'post') { const list=readUserArticles();const created={...body,id:nextId++,author:'Khách hàng',status:'DRAFT',createdAt:new Date().toISOString()};list.unshift(created);localStorage.setItem('mock_user_articles',JSON.stringify(list));result=created; }
  else if (path.startsWith('/user/articles/') && path.endsWith('/submit')) { const list=readUserArticles();const item=list.find((a:{id:number})=>a.id===Number(path.split('/')[3]));if(item)item.status='PENDING';localStorage.setItem('mock_user_articles',JSON.stringify(list));result=item; }
  else if (path === '/admin/users') result = [{ id: 1, fullName: 'Nguyễn Minh Tuấn', email: 'tuan@example.com', role: 'USER', status: 'ACTIVE' }, { id: 2, fullName: 'Trần Thu Hà', email: 'ha@example.com', role: 'USER', status: 'ACTIVE' }];
  else if (path === '/user/profile' && method === 'get') result = JSON.parse(localStorage.getItem('cokhi_user') || '{"fullName":"Khách hàng Bảo Tín","email":"khachhang@example.com","phone":"0983 755 949"}');
  else if (path === '/user/profile' && method === 'put') { const current=JSON.parse(localStorage.getItem('cokhi_user')||'{}');const user={...current,...body};localStorage.setItem('cokhi_user',JSON.stringify(user));result=user; }
  else if (path === '/user/addresses' && method === 'get') result = readAddresses();
  else if (path === '/user/addresses' && method === 'post') { const list=readAddresses();const address={...body,id:nextId++};if(address.isDefault)list.forEach((a:{isDefault:boolean})=>a.isDefault=false);list.unshift(address);localStorage.setItem('mock_addresses',JSON.stringify(list));result=list; }
  else if (path.startsWith('/user/addresses/') && method === 'delete') { const id=Number(path.split('/').pop());const list=readAddresses().filter((a:{id:number})=>a.id!==id);localStorage.setItem('mock_addresses',JSON.stringify(list));result=null; }
  else if (path === '/address/provinces') result = [{ code: 'HN', name: 'Hà Nội' }, { code: 'HP', name: 'Hải Phòng' }, { code: 'BN', name: 'Bắc Ninh' }, { code: 'HY', name: 'Hưng Yên' }, { code: 'HD', name: 'Hải Dương' }, { code: 'HCM', name: 'TP. Hồ Chí Minh' }];
  else if (path === '/address/wards') result = [{ code: 'P1', name: 'Xuân Đỉnh' }, { code: 'P2', name: 'Đông Anh' }, { code: 'P3', name: 'Bắc Từ Liêm' }, { code: 'P4', name: 'Nam Từ Liêm' }];
  else if (path === '/checkout' && method === 'post') { const list = readProducts(); const order = { orderCode: `BT-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 9000) + 1000)}`, customerName: body.customerName, customerPhone: body.customerPhone, customerEmail: body.customerEmail, shippingFullAddress: `${body.addressLine}, ${body.wardName}, ${body.provinceName}`, status: 'PENDING', items: (body.items || []).map((i: { productId: number; quantity: number }) => { const p = list.find((x: { id: number }) => x.id === i.productId)!; return { productId: p.id, productName: p.name, sku: p.sku, thumbnailUrl: p.thumbnailUrl, unitPrice: p.price || 0, quantity: i.quantity, subtotal: (p.price || 0) * i.quantity }; }), subtotal: 0, discount: 0, shippingFee: 0, vatAmount: 0, grandTotal: 0, payment: { method: body.paymentMethod || 'COD', status: 'PENDING', amount: 0, mock: true }, vat: body.vatRequested ? { ...body.vat, status: 'REQUESTED' } : null, createdAt: new Date().toISOString() }; order.subtotal = order.items.reduce((a: number, i: { subtotal: number }) => a + i.subtotal, 0); order.shippingFee = order.subtotal >= 5000000 ? 0 : 50000; order.vatAmount = body.vatRequested ? order.subtotal * 0.1 : 0; order.grandTotal = order.subtotal + order.shippingFee + order.vatAmount; const orders = readOrders(); orders.unshift(order); localStorage.setItem('mock_orders', JSON.stringify(orders)); result = order; }
  else if (path.startsWith('/orders/')) result = JSON.parse(localStorage.getItem('mock_orders') || '[]').find((o: { orderCode: string }) => o.orderCode === path.split('/').pop()) || null;
  else if (path === '/quotes' && method === 'post') { const quotes = JSON.parse(localStorage.getItem('mock_quotes') || '[]'); const quote = { ...body, id: nextId++, status: 'NEW', productName: products.find((p) => p.id === body.productId)?.name || 'Tư vấn hệ thống khí nén' }; quotes.unshift(quote); localStorage.setItem('mock_quotes', JSON.stringify(quotes)); result = quote; }
  else if (path.startsWith('/admin/orders/') && path.endsWith('/status')) { const orders = JSON.parse(localStorage.getItem('mock_orders') || '[]'); const code = path.split('/')[3]; const order = orders.find((o: { orderCode: string }) => o.orderCode === code); if (order) order.status = params.status; localStorage.setItem('mock_orders', JSON.stringify(orders)); result = order; }
  else if (path.startsWith('/admin/quotes/') && path.endsWith('/status')) { const quotes = readQuotes(); const q = quotes.find((x: { id: number }) => x.id === Number(path.split('/')[3])); if (q) q.status = params.status; localStorage.setItem('mock_quotes', JSON.stringify(quotes)); result = q; }
  else if (path.startsWith('/admin/vat-invoices/') && path.endsWith('/status')) { const vats = readVatRequests(); const v = vats.find((x: { id: number }) => x.id === Number(path.split('/')[3])); if (v) v.status = params.status; localStorage.setItem('mock_vats', JSON.stringify(vats)); result = v; }
  else if (path.startsWith('/admin/articles/') && path.endsWith('/moderate')) { const id=Number(path.split('/')[3]);const list=readUserArticles();const item=list.find((a:{id:number})=>a.id===id);if(item){item.status=params.status;localStorage.setItem('mock_user_articles',JSON.stringify(list));}else{const statuses=readArticleStatuses();statuses[id]=params.status;localStorage.setItem('mock_article_statuses',JSON.stringify(statuses));}result={status:params.status}; }
  else if (path === '/admin/uploads') result = { url: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=84' };
  else if ((path === '/admin/settings' || path === '/settings') && method === 'get') result = JSON.parse(localStorage.getItem('mock_settings') || '{"companyName":"Công ty TNHH Thiết bị Công nghiệp Văn Quân","hotline":"0946 678 168","email":"maynenkhibaotin@gmail.com","technicalPhone":"0983 755 949","address":"P.305, Tòa C2 Megastar, Xuân Đỉnh, Bắc Từ Liêm, Hà Nội","heroTitle":"Giải pháp khí nén cho nhà máy hiện đại","heroText":"Thiết bị chính hãng, tư vấn đúng tải và dịch vụ kỹ thuật đồng hành trong suốt vòng đời hệ thống."}');
  else if (path === '/admin/settings' && method !== 'get') { localStorage.setItem('mock_settings',JSON.stringify(body)); result=body; }
  else if (path.startsWith('/admin/') && method !== 'get') result = { success: true, status: params.status };
  else result = [];
  const response = { data: { data: result }, status: 200, statusText: 'OK', headers: {}, config } as AxiosResponse;
  return response;
};

export const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:8080/api/v1', timeout: 12000, adapter: import.meta.env.VITE_USE_REAL_API === 'true' ? undefined : mockAdapter });
api.interceptors.request.use((config) => { const token = localStorage.getItem('cokhi_token'); if (token) config.headers.Authorization = `Bearer ${token}`; return config; });
api.interceptors.response.use((r) => r, (e) => Promise.reject(new Error(e.response?.data?.message || 'Không thể kết nối máy chủ')));
export const unwrap = <T,>(r: { data: { data: T } }) => r.data.data;
